### ISSUE TITLE
Failure in compilation when attempting to add library already in library list

### ISSUE THREAD

**Issue by bmcpherson-srlife** [IBM/vscode-ibmi-projectexplorer#548]
Hello all!

I have observed a number of times when it comes to deploying projects which I am migrating to work with Project Explorer and Bob that listing a library in the .iproj.json file which already exists in my library list causes a compilation failure. I have provided a log below. Because of these projects, I am intentionally listing libraries which are dependencies of the project, but some have since been placed in the general user library list. I just wanted to point out this behavior. For now, I am simply listing the library list in the markdown, but I have been setting these up as a means for someone other than myself to easily pull a copy and make changes.

Thanks so much for all of the help!

`>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>  CHGCURLIB CURLIB(devlib)
>  ADDLIBLE LIB(utils) POSITION(*FIRST)
[FAILED]  ADDLIBLE LIB(utils) POSITION(*FIRST)
Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/python3.9/site-packages/ibm_db_dbi.py", line 1193, in _callproc_helper
    result = ibm_db.callproc(self.conn_handler, procname,parameters)
Exception: Statement Execute Failed: Trigger program or external routine detected an error. SQLSTATE=38501 SQLCODE=-443

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/bob/src/makei/crtfrmstmf.py", line 453, in <module>
    cli()
  File "/QOpenSys/pkgs/lib/bob/src/makei/crtfrmstmf.py", line 342, in cli
    success = handle.run()
  File "/QOpenSys/pkgs/lib/bob/src/makei/crtfrmstmf.py", line 100, in run
    self.setup_env()
  File "/QOpenSys/pkgs/lib/bob/src/makei/crtfrmstmf.py", line 157, in setup_env
    self.job.run_cl(f"ADDLIBLE LIB({libl}) POSITION(*FIRST)", log=True)
  File "/QOpenSys/pkgs/lib/bob/src/makei/ibm_job.py", line 39, in run_cl
    cursor.callproc("qsys2.qcmdexc", [cmd])
  File "/QOpenSys/pkgs/lib/python3.9/site-packages/ibm_db_dbi.py", line 1220, in callproc
    result = self._callproc_helper(procname, parameters)
  File "/QOpenSys/pkgs/lib/python3.9/site-packages/ibm_db_dbi.py", line 1196, in _callproc_helper
    raise self.messages[-1]
ibm_db_dbi.OperationalError: ibm_db_dbi::OperationalError: Exception('Statement Execute Failed: Trigger program or external routine detected an error. SQLSTATE=38501 SQLCODE=-443')
`

**Comment by SanjulaGanepola** [comment]
Hello @bmcpherson-srlife. Thank you for sharing this issue.

In testing this in Project Explorer, it looks like we don't observe any problem in the tree view because when constructing the library list we remove any duplicates when building the `liblist` command that will be called. I suppose this is an issue in itself as well since the user could have the same library in their `preUsrlibl` and `postUsrlibl` but not realize it is an issue. Although, it doesn't break the UI, the user should be made aware of this. Opened a new issue to track this -> https://github.com/IBM/vscode-ibmi-projectexplorer/issues/549

As for the specific issue you mentioned, this would require a change in how Bob constructs the library list.
@edmundreinhardt Since it is definitely possible that a library relevant for the project is also in the user library list defined on the user profile, how do you think Bob can handle this?

**Comment by AIforIBMi** [comment]
> As for the specific issue you mentioned, this would require a change in how Bob constructs the library list. @edmundreinhardt Since it is definitely possible that a library relevant for the project is also in the user library list defined on the user profile, how do you think Bob can handle this?

I guess the assumption was that if it was in the user JOBD then it would not need to be added by iproj.json, but I can see that this might not be true in general.
I am opening a defect on BOB to recover from that error and keep going.
https://github.com/IBM/ibmi-bob/issues/335

**Comment by AIforIBMi** [comment]
I think that philosophy is that User JOBD always takes priority - but, I have to admit that for build reproducibility your option 1 would be better.  I have to see if that is even feasible in a made/sh environment
@irfanshar let us know if you CAN implement # 1
